# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90e5b4200a845623d5bc4890756a967aab1cac767116581e1feaae4a83deaa50a821e132bf8ecb9e4b11f27228526b5cd9fb2315a5165f4f6d263ce6f4da72aa

test:
  secret_key_base: 842d3624422bf07778012cbf6259095e57e92481edba941e1a23acc37098110b1db95b6c4d5df046812a893c3dc712713651d1fe893fc93d5a6eeede81e171e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
